### PR TITLE
Updating to Swift 3

### PR DESCRIPTION
**Pull request by jackcolley**

### CODE REVIEW

**Comment by jackcolley** [comment]
#43

**Comment by CaptainMack** [comment]
Thanks @jackcolley! Hopefully it will be merged soon.

**Comment by blalger** [comment]
Thanks @jackcolley!  Quick question: do you know if it is possible to link to an unmerged commit in the Podfile?  I couldn't figure that out and just applied the changes locally.

**Comment by daltoniam** [comment]
Thanks!

**Pull request merged**
